proto < ../proto/auth.proto
@host=localhost:50051

### Success
GRPC /Auth/Login
{
    "email":"felis@gmail.om",
    "password": "felis123"
}

### Failed
GRPC /Auth/Login
{
    "email": "felis@mail.com",
    "password": ""
}