proto < ../proto/book.proto
@host=localhost:50051
{{+
  const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJpc3MiOiJhdXRoVG9rZW4iLCJleHAiOjE3MDIyODYxNDAsImlhdCI6MTcwMjI4MjU0MH0.3zdrCbcXC7RdFgWzUeeul6BDKadlFV-Z79zdnPPincE"
  exports.defaultHeaders = {
    'Content-Type': 'text/html',
    'Authorization': `Bearer ${token}`
  };
}}
### Success
GRPC /BookService/GetAllBook
...defaultHeaders
{
    
}