proto < ../proto/borrow.proto
@host=10.20.191.148:50051
{{+
  const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJpc3MiOiJhdXRoVG9rZW4iLCJleHAiOjE3MDIzNzc2MDgsImlhdCI6MTcwMjM3NDAwOH0.CRWgtEw2dnmKKbtZ5o2tNVbma1z_sb4uStuwESaXB1o"
  exports.defaultHeaders = {
    'Content-Type': 'text/html',
    'Authorization': `Bearer ${token}`
  };
}}

### Success
GRPC /Borrow/Borrow
...defaultHeaders
{
    "bookId":2, 
    "userId":1
}