version: '3.9'

services:
  postgresdb:
    image: postgres:16.1
    container_name: postgresql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/app
    env_file:
      - .env
    environment:
      - DB_HOST=postgresql
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - library_api  

volumes:
  api:

networks:
  library_api:
    driver: bridge
