// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/entity"
	mock "github.com/stretchr/testify/mock"
)

// BorrowingRecordUsecase is an autogenerated mock type for the BorrowingRecordUsecase type
type BorrowingRecordUsecase struct {
	mock.Mock
}

// AddBorrowingRecord provides a mock function with given fields: br
func (_m *BorrowingRecordUsecase) AddBorrowingRecord(br *entity.BorrowingRecords) (*entity.BorrowingRecords, error) {
	ret := _m.Called(br)

	var r0 *entity.BorrowingRecords
	if rf, ok := ret.Get(0).(func(*entity.BorrowingRecords) *entity.BorrowingRecords); ok {
		r0 = rf(br)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.BorrowingRecords)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.BorrowingRecords) error); ok {
		r1 = rf(br)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBorrowingRecordUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewBorrowingRecordUsecase creates a new instance of BorrowingRecordUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBorrowingRecordUsecase(t mockConstructorTestingTNewBorrowingRecordUsecase) *BorrowingRecordUsecase {
	mock := &BorrowingRecordUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
