// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/entity"
	mock "github.com/stretchr/testify/mock"

	valueobject "git.garena.com/sea-labs-id/bootcamp/batch-02/shared-projects/library-api/valueobject"
)

// BorrowingRecordRepository is an autogenerated mock type for the BorrowingRecordRepository type
type BorrowingRecordRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: t
func (_m *BorrowingRecordRepository) Create(t *entity.BorrowingRecords) (*entity.BorrowingRecords, error) {
	ret := _m.Called(t)

	var r0 *entity.BorrowingRecords
	if rf, ok := ret.Get(0).(func(*entity.BorrowingRecords) *entity.BorrowingRecords); ok {
		r0 = rf(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.BorrowingRecords)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.BorrowingRecords) error); ok {
		r1 = rf(t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: query
func (_m *BorrowingRecordRepository) Find(query valueobject.Query) []*entity.BorrowingRecords {
	ret := _m.Called(query)

	var r0 []*entity.BorrowingRecords
	if rf, ok := ret.Get(0).(func(valueobject.Query) []*entity.BorrowingRecords); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.BorrowingRecords)
		}
	}

	return r0
}

// First provides a mock function with given fields: query
func (_m *BorrowingRecordRepository) First(query valueobject.Query) *entity.BorrowingRecords {
	ret := _m.Called(query)

	var r0 *entity.BorrowingRecords
	if rf, ok := ret.Get(0).(func(valueobject.Query) *entity.BorrowingRecords); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.BorrowingRecords)
		}
	}

	return r0
}

type mockConstructorTestingTNewBorrowingRecordRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBorrowingRecordRepository creates a new instance of BorrowingRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBorrowingRecordRepository(t mockConstructorTestingTNewBorrowingRecordRepository) *BorrowingRecordRepository {
	mock := &BorrowingRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
