// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/borrow.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BorrowClient is the client API for Borrow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BorrowClient interface {
	Borrow(ctx context.Context, in *BorrowRequest, opts ...grpc.CallOption) (*BorrowResponse, error)
}

type borrowClient struct {
	cc grpc.ClientConnInterface
}

func NewBorrowClient(cc grpc.ClientConnInterface) BorrowClient {
	return &borrowClient{cc}
}

func (c *borrowClient) Borrow(ctx context.Context, in *BorrowRequest, opts ...grpc.CallOption) (*BorrowResponse, error) {
	out := new(BorrowResponse)
	err := c.cc.Invoke(ctx, "/borrow.Borrow/Borrow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BorrowServer is the server API for Borrow service.
// All implementations must embed UnimplementedBorrowServer
// for forward compatibility
type BorrowServer interface {
	Borrow(context.Context, *BorrowRequest) (*BorrowResponse, error)
	mustEmbedUnimplementedBorrowServer()
}

// UnimplementedBorrowServer must be embedded to have forward compatible implementations.
type UnimplementedBorrowServer struct {
}

func (UnimplementedBorrowServer) Borrow(context.Context, *BorrowRequest) (*BorrowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Borrow not implemented")
}
func (UnimplementedBorrowServer) mustEmbedUnimplementedBorrowServer() {}

// UnsafeBorrowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BorrowServer will
// result in compilation errors.
type UnsafeBorrowServer interface {
	mustEmbedUnimplementedBorrowServer()
}

func RegisterBorrowServer(s grpc.ServiceRegistrar, srv BorrowServer) {
	s.RegisterService(&Borrow_ServiceDesc, srv)
}

func _Borrow_Borrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BorrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowServer).Borrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/borrow.Borrow/Borrow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowServer).Borrow(ctx, req.(*BorrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Borrow_ServiceDesc is the grpc.ServiceDesc for Borrow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Borrow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "borrow.Borrow",
	HandlerType: (*BorrowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Borrow",
			Handler:    _Borrow_Borrow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/borrow.proto",
}
